import type { NextPage } from "next";
import Head from "next/head";
import Navigation from "@/components/nav/nav";
import Header from "@/components/header/header";
import FirstIntro from "@/components/home/firstIntro";
import SecondIntro from "@/components/home/secondIntro";
import Pricing from "@/components/home/pricing";
import DownloadSection from "@/components/home/download";
import ServicesSection from "@/components/home/services";
import CallToAction from "@/components/home/callToAction";
import BaseLayout from "@/components/layouts/base";
import ManageExchanges from "@/components/home/manageExchanges";
import Blog from "@/components/blog/blogCard";
import Blogs from "@/components/home/blogs";
import Announcements from "@/components/home/announcements";

const Home: NextPage = (): JSX.Element => {
	return (
		<div>
			<Head>
				<title>کمپر کریپتو</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<BaseLayout>
				<Header />
				<FirstIntro />
				<SecondIntro />
				<ManageExchanges />
				<Pricing />
				<CallToAction
					title="امروز را با یک دوره آزمایشی رایگان سفارشی امتحان کنید"
					description="
					لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده
					از چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است.
				"
					buttonName="شروع کنید"
				/>
				<ServicesSection />
				<Blogs />
				<Announcements />
				<DownloadSection />
			</BaseLayout>
		</div>
	);
};

export default Home;
