import type { NextPage } from "next";
import Head from "next/head";
import Navigation from "@/components/nav/nav";
import Header from "@/components/header/header";
import FirstIntro from "@/components/home/firstIntro";
import SecondIntro from "@/components/home/secondIntro";
import Pricing from "@/components/home/pricing";
import DownloadSection from "@/components/home/download";

const Home: NextPage = (): JSX.Element => {
	return (
		<div>
			<Head>
				<title>کمپر کریپتو</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Navigation />
			<Header />
			<FirstIntro />
			<SecondIntro />
			<Pricing />
			<DownloadSection />
		</div>
	);
};

export default Home;
